### ISSUE TITLE
Emulate Persistent Memory

### ISSUE THREAD

**Issue by Legend147** [Andiry/pmfs-3.19#1]
Hello, Andiry. Really great Work!!!
I have some confusions about how to emulate persistent memory for testing pmfs. The Persistent Latency and Bandwidth are very important factor for performance of system on NVM-based memory. Are there any way to deal with it easily ?

**Comment by Andiry** [comment]
You need the Intel PM emulation platform to adjust the latency and bandwidth. There is no easy way to deal with it.

**Comment by Legend147** [comment]
Thank you very much. But as far as I know the Intel PM emulation platform which was described in the paper "System software for persistent memory" requires special hardware and firmware. I don't know how to set up the simulation. Is there a way I can get the PMEP? Otherwise, I find the website
http://pmem.io/2016/02/22/pm-emulation.html, but it don't emulate latency and bandwith. Thank you again

**Comment by Andiry** [comment]
That is correct. PMEP is developed by Intel with special hardware and firmware. The platform is located at Intel and we use ssh to remote access it. You have to contact Intel to get access to it.

**Comment by Legend147** [comment]
Thank you very much!!!
