### ISSUE TITLE
Can I ask you a question?

### ISSUE THREAD

**Issue by iDalink** [Andiry/pmfs-3.19#2]
I am developing my own file system. Unfortunately linux kernel throws an error. So, how can I debug it?
How do you solve this error when kernel occur an error?
My contact email is 934367813@qq.com. Thanks!

**Comment by Andiry** [comment]
This question is too general. It depends on what error the kernel throws. I cannot help you without detail information.

**Comment by iDalink** [comment]
Can I have your email?
